//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MHealthKiosk.MhealthKioskService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MhealthKioskService.IMHealthKioskService")]
    public interface IMHealthKioskService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMHealthKioskService/AddVisit", ReplyAction="http://tempuri.org/IMHealthKioskService/AddVisitResponse")]
        string AddVisit(string DeviceInfo, string NationalID, string MobileNumber, string Systolic, string Diastolic, string SPO2Percentage, string SPO2PulseRate);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMHealthKioskServiceChannel : MHealthKiosk.MhealthKioskService.IMHealthKioskService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MHealthKioskServiceClient : System.ServiceModel.ClientBase<MHealthKiosk.MhealthKioskService.IMHealthKioskService>, MHealthKiosk.MhealthKioskService.IMHealthKioskService {
        
        public MHealthKioskServiceClient() {
        }
        
        public MHealthKioskServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MHealthKioskServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MHealthKioskServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MHealthKioskServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string AddVisit(string DeviceInfo, string NationalID, string MobileNumber, string Systolic, string Diastolic, string SPO2Percentage, string SPO2PulseRate) {
            return base.Channel.AddVisit(DeviceInfo, NationalID, MobileNumber, Systolic, Diastolic, SPO2Percentage, SPO2PulseRate);
        }
    }
}
